global:
  user: tidb
  ssh_port: 22
  ssh_type: builtin
  deploy_dir: /home/tidb/tidb-deploy
  data_dir: /home/tidb/tidb-data
  os: linux
  systemd_mode: system
monitored:
  node_exporter_port: 9100
  blackbox_exporter_port: 9115
  deploy_dir: /home/tidb/tidb-deploy/monitor-9100
  data_dir: /home/tidb/tidb-data/monitor-9100
  log_dir: /home/tidb/tidb-deploy/monitor-9100/log
server_configs:
  tidb:
    graceful-wait-before-shutdown: 15
    instance.tidb_slow_log_threshold: 300
    max-index-length: 6144
  tikv:
    raftstore.capacity: 1024GiB
    readpool.coprocessor.use-unified-pool: true
    readpool.storage.use-unified-pool: true
    readpool.unified.max-thread-count: 6
    storage.block-cache.capacity: 16GiB
  pd:
    replication.enable-placement-rules: true
    replication.location-labels:
    - zone
    - host
    replication.replicas: 5
  tso: {}
  scheduling: {}
  tidb_dashboard: {}
  tiflash: {}
  tiproxy: {}
  tiflash-learner: {}
  pump: {}
  drainer: {}
  cdc: {}
  kvcdc: {}
  grafana: {}
tidb_servers:
- host: 172.19.4.138
  ssh_port: 22
  port: 4000
  status_port: 10080
  deploy_dir: /home/tidb/tidb-deploy/tidb-4000
  log_dir: /home/tidb/tidb-deploy/tidb-4000/log
  config:
    security.session-token-signing-cert: /home/tidb/tidb-deploy/tidb-4000/tls/tiproxy-session.crt
    security.session-token-signing-key: /home/tidb/tidb-deploy/tidb-4000/tls/tiproxy-session.key
  arch: amd64
  os: linux
- host: 172.19.2.134
  ssh_port: 22
  port: 4000
  status_port: 10080
  deploy_dir: /home/tidb/tidb-deploy/tidb-4000
  log_dir: /home/tidb/tidb-deploy/tidb-4000/log
  config:
    security.session-token-signing-cert: /home/tidb/tidb-deploy/tidb-4000/tls/tiproxy-session.crt
    security.session-token-signing-key: /home/tidb/tidb-deploy/tidb-4000/tls/tiproxy-session.key
  arch: amd64
  os: linux
- host: 172.19.2.138
  ssh_port: 22
  port: 4000
  status_port: 10080
  deploy_dir: /home/tidb/tidb-deploy/tidb-4000
  log_dir: /home/tidb/tidb-deploy/tidb-4000/log
  config:
    security.session-token-signing-cert: /home/tidb/tidb-deploy/tidb-4000/tls/tiproxy-session.crt
    security.session-token-signing-key: /home/tidb/tidb-deploy/tidb-4000/tls/tiproxy-session.key
  arch: amd64
  os: linux
tikv_servers:
- host: 172.19.2.134
  ssh_port: 22
  port: 20160
  status_port: 20180
  deploy_dir: /home/tidb/tidb-deploy/tikv-20160
  data_dir: /home/tidb/tidb-data/tikv-20160
  log_dir: /home/tidb/tidb-deploy/tikv-20160/log
  config:
    server.labels:
      host: host-3
      zone: az-2
  arch: amd64
  os: linux
- host: 172.19.2.134
  ssh_port: 22
  port: 20161
  status_port: 20181
  deploy_dir: /home/tidb/tidb-deploy/tikv-20161
  data_dir: /home/tidb/tidb-data/tikv-20161
  log_dir: /home/tidb/tidb-deploy/tikv-20161/log
  config:
    server.labels:
      host: host-4
      zone: az-2
  arch: amd64
  os: linux
- host: 172.19.2.138
  ssh_port: 22
  port: 20160
  status_port: 20180
  deploy_dir: /home/tidb/tidb-deploy/tikv-20160
  data_dir: /home/tidb/tidb-data/tikv-20160
  log_dir: /home/tidb/tidb-deploy/tikv-20160/log
  config:
    server.labels:
      host: host-5
      zone: az-3
  arch: amd64
  os: linux
- host: 172.19.2.138
  ssh_port: 22
  port: 20161
  status_port: 20181
  deploy_dir: /home/tidb/tidb-deploy/tikv-20161
  data_dir: /home/tidb/tidb-data/tikv-20161
  log_dir: /home/tidb/tidb-deploy/tikv-20161/log
  config:
    server.labels:
      host: host-6
      zone: az-3
  arch: amd64
  os: linux
- host: 172.19.4.138
  ssh_port: 22
  port: 20160
  status_port: 20180
  deploy_dir: /home/tidb/tidb-deploy/tikv-20160
  data_dir: /home/tidb/tidb-data/tikv-20160
  log_dir: /home/tidb/tidb-deploy/tikv-20160/log
  config:
    server.labels:
      host: host-1
      zone: az-1
  arch: amd64
  os: linux
- host: 172.19.4.138
  ssh_port: 22
  port: 20161
  status_port: 20181
  deploy_dir: /home/tidb/tidb-deploy/tikv-20161
  data_dir: /home/tidb/tidb-data/tikv-20161
  log_dir: /home/tidb/tidb-deploy/tikv-20161/log
  config:
    server.labels:
      host: host-2
      zone: az-1
  arch: amd64
  os: linux
tiflash_servers: []
tiproxy_servers:
- host: 172.19.4.138
  ssh_port: 22
  port: 6000
  status_port: 3080
  deploy_dir: /home/tidb/tidb-deploy/tiproxy-6000
  arch: amd64
  os: linux
- host: 172.19.2.134
  ssh_port: 22
  port: 6000
  status_port: 3080
  deploy_dir: /home/tidb/tidb-deploy/tiproxy-6000
  arch: amd64
  os: linux
- host: 172.19.2.138
  ssh_port: 22
  port: 6000
  status_port: 3080
  deploy_dir: /home/tidb/tidb-deploy/tiproxy-6000
  arch: amd64
  os: linux
pd_servers:
- host: 172.19.2.134
  ssh_port: 22
  name: pd-172.19.2.134-2379
  client_port: 2379
  peer_port: 2380
  deploy_dir: /home/tidb/tidb-deploy/pd-2379
  data_dir: /home/tidb/tidb-data/pd-2379
  log_dir: /home/tidb/tidb-deploy/pd-2379/log
  arch: amd64
  os: linux
- host: 172.19.2.134
  ssh_port: 22
  name: pd-172.19.2.134-2479
  client_port: 2479
  peer_port: 2480
  deploy_dir: /home/tidb/tidb-deploy/pd-2479
  data_dir: /home/tidb/tidb-data/pd-2479
  log_dir: /home/tidb/tidb-deploy/pd-2479/log
  arch: amd64
  os: linux
- host: 172.19.2.138
  ssh_port: 22
  name: pd-172.19.2.138-2379
  client_port: 2379
  peer_port: 2380
  deploy_dir: /home/tidb/tidb-deploy/pd-2379
  data_dir: /home/tidb/tidb-data/pd-2379
  log_dir: /home/tidb/tidb-deploy/pd-2379/log
  arch: amd64
  os: linux
- host: 172.19.2.138
  ssh_port: 22
  name: pd-172.19.2.138-2479
  client_port: 2479
  peer_port: 2480
  deploy_dir: /home/tidb/tidb-deploy/pd-2479
  data_dir: /home/tidb/tidb-data/pd-2479
  log_dir: /home/tidb/tidb-deploy/pd-2479/log
  arch: amd64
  os: linux
- host: 172.19.4.138
  ssh_port: 22
  name: pd-172.19.4.138-2379
  client_port: 2379
  peer_port: 2380
  deploy_dir: /home/tidb/tidb-deploy/pd-2379
  data_dir: /home/tidb/tidb-data/pd-2379
  log_dir: /home/tidb/tidb-deploy/pd-2379/log
  arch: amd64
  os: linux
cdc_servers:
- host: 172.19.4.138
  ssh_port: 22
  port: 8300
  deploy_dir: /home/tidb/tidb-deploy/cdc-8300
  data_dir: /home/tidb/tidb-data/cdc-8300
  log_dir: /home/tidb/tidb-deploy/cdc-8300/log
  gc-ttl: 86400
  ticdc_cluster_id: ""
  arch: amd64
  os: linux
- host: 172.19.2.134
  ssh_port: 22
  port: 8300
  deploy_dir: /home/tidb/tidb-deploy/cdc-8300
  data_dir: /home/tidb/tidb-data/cdc-8300
  log_dir: /home/tidb/tidb-deploy/cdc-8300/log
  ticdc_cluster_id: ""
  arch: amd64
  os: linux
- host: 172.19.2.138
  ssh_port: 22
  port: 8300
  deploy_dir: /home/tidb/tidb-deploy/cdc-8300
  data_dir: /home/tidb/tidb-data/cdc-8300
  log_dir: /home/tidb/tidb-deploy/cdc-8300/log
  ticdc_cluster_id: ""
  arch: amd64
  os: linux
monitoring_servers:
- host: 172.19.4.138
  ssh_port: 22
  port: 9090
  ng_port: 12020
  deploy_dir: /home/tidb/tidb-deploy/prometheus-9090
  data_dir: /home/tidb/tidb-data/prometheus-9090
  log_dir: /home/tidb/tidb-deploy/prometheus-9090/log
  external_alertmanagers: []
  arch: amd64
  os: linux
grafana_servers:
- host: 172.19.4.138
  ssh_port: 22
  port: 3000
  deploy_dir: /home/tidb/tidb-deploy/grafana-3000
  arch: amd64
  os: linux
  username: admin
  password: admin
  anonymous_enable: false
  root_url: ""
  domain: ""
alertmanager_servers:
- host: 172.19.4.138
  ssh_port: 22
  web_port: 9093
  cluster_port: 9094
  deploy_dir: /home/tidb/tidb-deploy/alertmanager-9093
  data_dir: /home/tidb/tidb-data/alertmanager-9093
  log_dir: /home/tidb/tidb-deploy/alertmanager-9093/log
  arch: amd64
  os: linux
